### ISSUE TITLE
Page dot indicator

### ISSUE THREAD

**Issue by hyouuu** [JanGorman/Agrume#100]
Currently doesn't seem to support this feature, and I might get time in the future to make it, but wanted to throw it out here first - any thoughts or existing approaches?

**Comment by hemangshah** [comment]
Like sliding?

**Comment by hyouuu** [comment]
Reopen as this is till a really nice to have feature

**Comment by hyouuu** [comment]
Mmm seems I can't re-open cc @JanGorman
