### ISSUE TITLE
didScroll cannot be used

### ISSUE THREAD

**Issue by rausnitz** [JanGorman/Agrume#102]
https://github.com/JanGorman/Agrume/blob/58f10628b026fc8bf3e9708589800ee041839835/Agrume/Agrume.swift#L22
`didScroll` is defined but is never actually used in the code base. I've tried using `didScroll` but it never gets called. It looks like it was implemented in a previous version of Agrume but forgotten in version 5.

**Comment by JanGorman** [comment]
Which would explain #82. Thanks for the report
