### ISSUE TITLE
The example does not seem to build ?

### ISSUE THREAD

**Issue by 10000TB** [JanGorman/Agrume#103]

**Comment by JanGorman** [comment]
![Screenshot 2019-03-20 at 09 12 18](https://user-images.githubusercontent.com/138166/54668905-575f9880-4af0-11e9-90eb-47d8f4411725.png)

Works on my machine™. Which version of Xcode are you using?

**Comment by 10000TB** [comment]
Version 10.1 (10B61)

**Comment by 10000TB** [comment]
I figure it might have been due to that I was using Swift 4 and downloaded latest version of `Agrume`, which instead is in 4.2

**Comment by JanGorman** [comment]
Ok, I hope it's fine now
