### ISSUE TITLE
Having error after swift update

### ISSUE THREAD

**Issue by UtkuDalmaz** [JanGorman/Agrume#105]
In ImageDownloader.swift

`Call can throw, but it is not marked with 'try' and the error is not handled
`
![Screen Shot 2019-04-12 at 17 51 07](https://user-images.githubusercontent.com/2130592/56046305-a09bb480-5d4b-11e9-9415-c87b679da90f.png)

How to fix this?

Thanks

**Comment by chauhan130** [comment]
@UtkuDalmaz That issue is already fixed on master 5 days back (see @anilgoktas commit https://github.com/JanGorman/Agrume/commit/324e09ac9ae89789c56afb824ba1631c35f91b32).

Use `pod 'Agrume', :git => 'https://github.com/JanGorman/Agrume'` till ge get new release.

**Comment by JanGorman** [comment]
Just pushed 5.3.1 – Thanks

**Comment by RobSwish** [comment]
I have just installed the latest version and I get the above issue. Is this correct?

**Comment by JanGorman** [comment]
@RobSwish I just tested this on a new test project and it correctly pulled 5.3.1:
```sh
➜  Foo git:(master) ✗ pod install
Analyzing dependencies
Downloading dependencies
Installing Agrume (5.3.1)
Installing SwiftyGif (5.0.0)
Generating Pods project
Integrating client project
```

Can you try running `pod update Agrume` – as far as I recall this will force an update of the specs repository
