### ISSUE TITLE
Image not loading fully

### ISSUE THREAD

**Issue by nishan-p** [JanGorman/Agrume#110]
I have tried integrating this library but the image is not showing fully. What can be the issue. Please check this screenshot for the screen which i'm receiving after adding this library and when previewing the image [https://www.dropbox.com/s/i8vxmsfy8v4wtf5/ImageNotFull.png?dl=0](url)

**Comment by JanGorman** [comment]
Sorry to hear you're having issues with the integration. Can you shed some light on what's the expected outcome, it's a bit hard to tell from just the screenshot alone. Is the image off-center, i.e. should it be shifted to the right more? Is it a remote or local image?

**Comment by nishan-p** [comment]
Yeah it should show the full image, i.e. it should get shifted to more to the right. It should show the full width of the screen.

**Comment by JanGorman** [comment]
Would it be possible for you to share the image and the code used to display it with me?

**Comment by nishan-p** [comment]
Image is the default image of the simulator and this is the code`let agrume = Agrume.init(image: image, background: .blurred(.extraLight), dismissal: .withPhysics)
                agrume.show(from: self)`

**Comment by nishan-p** [comment]
@JanGorman any update on the same ? Is it issue with the frame its setting or is there anything to do with the library itself ?

**Comment by JanGorman** [comment]
I tried it with the same image:
![Screenshot 2019-06-24 at 10 06 11](https://user-images.githubusercontent.com/138166/60001930-e3d9a400-9667-11e9-8300-82708f636729.png)

That looks fine. Did you try on a bare bones app or is it integrating with an existing one?

**Comment by JanGorman** [comment]
Closed for lack of activity
