### ISSUE TITLE
Animated GIF issue since 5.3.2

### ISSUE THREAD

**Issue by allaire** [JanGorman/Agrume#140]
Hi,

We were running Agrume version 5.3.1, but when we upgraded to latest, we noticed that GIFs are not working correctly anymore in our app.

On open, the GIF is out of bounds / not displaying. You can make it appear by just doing a quick gesture on the screen. We pinpointed the regression in 5.3.2.

I think it has to do the use of `UIImage(gifData:)`.

Here's our code sample:

```swift
            let isGIF = viewModel.originalImageUrl?.contains(".gif") ?? false
            
            if let imageData = viewModel.originalImageData, isGIF, let gifImage = try? UIImage(gifData: imageData) {
                image = gifImage
            }
            
            let agrume = Agrume(image: image, background: .blurred(.dark))
```

**Comment by JanGorman** [comment]
Sorry to hear that you're having issues. I will take a look today

**Comment by JanGorman** [comment]
I can't make the connection to that release specifically – even if I undo the change made there it does not work. But I have a lead that the imageView's frame is `.zero` initially

**Comment by allaire** [comment]
@JanGorman Yes exactly, my thoughts exactly about the frame being zero, so it's not centered/displayed. Probably there is less info about the frame in `UIImage` when initiated from `UIImage(gifData:)`

**Comment by JanGorman** [comment]
Found it. Release on the way. Unsure why this was not an issue before tbh
