### ISSUE TITLE
cannot run didScroll correctly. why use backgroundImageView?

### ISSUE THREAD

**Issue by Alexookah** [JanGorman/Agrume#152]
I noticed that in the example for multiple images:
`agrume.didScroll = { [unowned self] index in
  self.collectionView.scrollToItem(at: IndexPath(item: index, section: 0), at: [], animated: false)
}`
does not work because the UIViewController behind Agrume is not really shown.
When using blur a backgroundImageView is taking some snapshot which is between UIViewController and Agrume.
What's the usage of backgroundImageView?

after it is dismissed for some reason the didScroll function is being called with some delay in the change.

**Comment by JanGorman** [comment]
IIRC this was a workaround for a bug at the time that it didn't take the correct snapshot and this was a way to pass in the correct view for it to snapshot. This functionality can probably be removed

**Comment by Alexookah** [comment]
@JanGorman 
https://streamable.com/szwtf
I can see that its not working correctly in presenting mode. I agree this should be removed. Should i make a PL?

**Comment by Alexookah** [comment]
@JanGorman 
I see you did some cleanup. Did you have a chance to check BackgroundImageView if the functionality can be removed eventually.

**Comment by JanGorman** [comment]
It was only a quick 15 mins of cleanup when I got home yesterday. If you have time to check this further please feel free to do so

**Comment by JanGorman** [comment]
I'm on it. My earlier statement was about something else, I got the two mixed up. So… reason to have the background image view was back then (I wrote the first version 5 years ago 😅) blurring was a bit of a performance concern but indeed these days not an issue. I'll push something shortly
