### ISSUE TITLE
WEBP url is not loading

### ISSUE THREAD

**Issue by h0s0n** [JanGorman/Agrume#158]
I need to use webp images in agrume but the urls of webp are not showing.

**Comment by JanGorman** [comment]
Yes, it's not a format that Apple supports natively. I'm aware of at least one wrapper library https://github.com/ainame/Swift-WebP though that does not support CocoaPods.
PRs are welcome

**Comment by Alexookah** [comment]
@h0s0n you can also a CustomDownloadHandler and use SDWebImage to download images.
