### ISSUE TITLE
Crash when using custom AgrumeDataSource

### ISSUE THREAD

**Issue by ryan-w** [JanGorman/Agrume#163]
Providing a custom data source causes a crash on the following line:
 
https://github.com/JanGorman/Agrume/blob/13c60342c1d9ae0e64a9e62c83abce512381f654/Agrume/Agrume.swift#L428

Message: "Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value"

The 'images' property is not initialized when using a custom data source. It would be better to remove this line of code as it is only there to support the "onLongPress" function. The "onLongPress" function could access the current image through the 'dataSource' property instead which should work for all use cases and removes the unnecessary duplication of image storage.

**Comment by JanGorman** [comment]
Thanks for reporting! Yes, that's a good point. I had my doubts about that line while reviewing and didn't fully think it through. Sorry

**Comment by ryan-w** [comment]
@JanGorman Thank you.
