### ISSUE TITLE
webP format

### ISSUE THREAD

**Issue by philCc** [JanGorman/Agrume#181]
Should support WebP?

**Comment by JanGorman** [comment]
If you can suggest a library I can look into integrating it. Since I personally have no need to support WebP it's not included :)
Pull requests welcome

**Comment by philCc** [comment]
I think we can take the picture decoder as a plug-in separately, and integrate one or two picture decoders by default

like the library [Kingfisher](https://github.com/onevcat/Kingfisher)
```swift
KingfisherManager.shared.defaultOptions += [
  .processor(WebPProcessor.default),
  .cacheSerializer(WebPSerializer.default)
]
```

https://github.com/SDWebImage/libwebp-Xcode

https://github.com/yeatse/KingfisherWebP
