### ISSUE TITLE
When navigation controller is set to portrait only the image view will mess that up if rotated when opened

### ISSUE THREAD

**Issue by ChrisStayte** [JanGorman/Agrume#20]

**Comment by JanGorman** [comment]
Thanks for the report. Could you share a screenshot what you mean by messed up? Just to be sure we're referring to the same thing – I see what you mean on the simulator since it does that forced last rotation thing when you open the view again but on a real device it works fine.

Could you also just verify your case on a  device and let me know.

Thanks!

**Comment by ChrisStayte** [comment]
I am running this on an iPhone 6s plus 128 gb space grey. I have attached a link to a video recording of my iPhone screen so you can view the error. What I am doing is first tapping on the photo which brings up the image in portrait mode. This works great. While the photo is still being presented I rotate my phone and the image rotates great. Then as you can see I dismiss the photo and then I rotate my phone but keep in mind the view controller with the image on it is not allowed to go into landscape and only portrait so i tap on the photo with the phone in landscape and it appears as the photo is on the left side of the screen in portrait width. 


https://www.dropbox.com/s/dlxtsj03dvvm3f7/Error.mov?dl=0

**Comment by JanGorman** [comment]
Thanks so much, that makes it much clearer! I got the same effect on the simulator but not on the device – I'll play around some more and try to reproduce (and of course come up with a fix).

**Comment by ChrisStayte** [comment]
Thank you! :)

**Comment by JanGorman** [comment]
Could you test out this branch https://github.com/JanGorman/Agrume/tree/fix-rotation in your project and let me know if that fixes the issue for you?

**Comment by ChrisStayte** [comment]
Am I able to pull that using my pod file or do I have to copy it manually?

**Comment by JanGorman** [comment]
You can reference the branch in your Podfile:

`pod 'Agrume', :git => 'git@github.com:JanGorman/Agrume.git', :branch => 'fix-rotation'`

**Comment by ChrisStayte** [comment]
Thanks, this did fix the issue :)

**Comment by JanGorman** [comment]
💃 Cool – then I'll merge this back and push a new release. Thanks for all your help getting this resolved

**Comment by ChrisStayte** [comment]
Thank you for the quick reply and the quick fix. You are a life saver :)
