### ISSUE TITLE
minimum deployment target issue 

### ISSUE THREAD

**Issue by geekyfox90** [JanGorman/Agrume#21]
Suddenly I'm getting an error

> Module file's minimum deployment target is ios8.3

it must to have a problem with the last version of Cocoapods 1.0.0 released may 10th

**Comment by JanGorman** [comment]
Hi,

I bumped it to 8.3 with this [commit](https://github.com/JanGorman/Agrume/commit/8b42b0a4fca0ae0048931f5503b6ea2efbd043ee) – glancing over it right now I can't remember why. I won't have time before Tuesday to look into it but I'll get back to you.

**Comment by geekyfox90** [comment]
Hi, thanks for your answer, it would be great to get it back to 8.0

Thanks

**Comment by JanGorman** [comment]
Fixed with [b0011b7](https://github.com/JanGorman/Agrume/commit/b0011b78439078dd27e02a53406f83bc9eef6f9c) – the Xcode project itself was still set to 8.0 so no idea what I was thinking. Let me know if it works fine for you.

Thanks!

**Comment by geekyfox90** [comment]
Sorry for late response ! it works perfectly, thanks again

**Comment by JanGorman** [comment]
👏 glad to hear it, thanks for raising the issue
