### ISSUE TITLE
Cannot find type 'Agrume' in scope

### ISSUE THREAD

**Issue by gouravideal** [JanGorman/Agrume#235]
got this crash in agrume.swift

Printing description of self:
expression produced error: error: /var/folders/yh/2x5wsjps5n1byqbhl95h_rmm0000gn/T/expr30-1e0641..swift:1:65: error: cannot find type 'Agrume' in scope
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<Agrume.Agrume>(bitPattern: 0x10d02ca60)!.pointee)

@JanGorman please help me for resolve this crash..
![Screenshot 2020-11-24 at 12 38 22 PM](https://user-images.githubusercontent.com/61136324/100061061-7da41280-2e53-11eb-80f2-c034a069a714.png)

**Comment by JanGorman** [comment]
If I had to guess, this looks like you're not retaining your Agrume instance. You'll want to create a property in your class to hold on to it. The included Example directory shows how. For example https://github.com/JanGorman/Agrume/blob/master/Example/Agrume%20Example/SingleImageViewController.swift#L10

**Comment by gouravideal** [comment]
hi @JanGorman. i will try for this but not working for me. can we use this with [week self]. because its working correctly for me can you suggest me this working properly or not for resolving this crash. if you can change this in directly is best for us.

After change code like this :

        presentingViewController?.dismiss(animated: false) { [weak self] in
            guard let self = self else { return }
            self.cleanup()
            self.didDismiss?()
        }

**Comment by gouravideal** [comment]
@JanGorman  i am waiting for your response

**Comment by JanGorman** [comment]
Can you share a bit more of the code that's causing this crash. Because this should not be a problem using `unowned` since the UIViewController that's shown will be retained. I gave it a quick try
```swift
@IBAction private func openImage(_ sender: Any) {
    let agrume = Agrume(image: UIImage(named: "MapleBacon")!, background: .blurred(.regular))
    agrume.didDismiss = {
      print("foo")
    }
    agrume.show(from: self)
  }
```
And this works just fine

**Comment by gouravideal** [comment]
Hello @JanGorman thanks for your response. but this solution not worked for me crash is going on after this... i use agrume code in my project like this. please suggest me for this crash solution. this crash not happen with [weak self] in your pod... please help me... 

import Agrume
import AlamofireImage
import UIKit

extension UIViewController {
       func present(_ photo: PhotoContract, delegate: OverlayViewDelegate? = nil) {
        AgrumeServiceLocator.shared.setDownloadHandler { url, completion in
            // Download data, cache it and call the completion with the resulting UIImage
            dispatchAsync(qos: .utility) {
                ImageResponseSerializer.addAcceptableImageContentTypes([Constants.ContentType.jpg])

                UIImageView
                    .af
                    .sharedImageDownloader
                    .download(URLRequest(url: url), completion: { response in
                        switch response.result {
                        case .success(let image):
                            completion(image)
                        case .failure(let error):
                            completion(R.image.photo.notFound())
                        }
                    })
            }
        }

        guard let notFoundImage = R.image.photo.notFound() else { return }
        let overlay = OverlayView()
        overlay.delegate = delegate
        overlay.photo = photo
        let agrume = Agrume(image: notFoundImage,
                            overlayView: overlay)
        agrume.didDismiss = {
            print("*********** foo didDismiss***********")
        }
        agrume.show(from: self)

        if let imageURL = photo.remotePhoto {
            agrume.updateImage(at: 0, with: imageURL)
        }
    }
}

**Comment by JanGorman** [comment]
I tried to replicate what you have, it still works. There must be something else going on. Just a suggestion, the way you're using `AlamofireImage` can be improved, accessing the downloader through the `UIImageView` extension is not exactly straightforward. Can you try your code in a standalone project

Here's my example:

```swift
import Agrume
import Alamofire
import AlamofireImage
import UIKit

final class ViewController: UIViewController {

  @IBAction func press(_ sender: Any) {
    present(URL(string: "https://i.picsum.photos/id/866/200/300.jpg?hmac=rcadCENKh4rD6MAp6V_ma-AyWv641M4iiOpe1RyFHeI")!)
  }

}

extension UIViewController {
  func present(_ url: URL) {
    AgrumeServiceLocator.shared.setDownloadHandler { url, completion in
      ImageDownloader().download(URLRequest(url: url), completion:  { response in
        guard case let .success(image) = response.result else {
          completion(nil)
          return
        }
        completion(image)
      })
    }

    let overlay = Overlay()
    let agrume = Agrume(image: UIImage(named: "placeholder")!, overlayView: overlay)
    agrume.didDismiss = {
      print("foo")
    }
    agrume.show(from: self)
  }
}

final class Overlay: AgrumeOverlayView {

}
```
