### ISSUE TITLE
The image is not centered

### ISSUE THREAD

**Issue by meme17sk** [JanGorman/Agrume#246]
I’m using Agrume to display an image on my swift application.
But the image is not centered. I have to click in order to bring it to the center.
It is located to the left and when I click it goes to the center.
I’m displaying a single image.
Could you please help me?
Thank you

**Comment by meme17sk** [comment]
@JanGorman please help me to solve this issue. Thank you

**Comment by JanGorman** [comment]
Can you shed some light on how you're using the library, what kind of image is showing, basically anything

As you may have seen the library ships with a sample project and when I run that locally it works fine: https://github.com/JanGorman/Agrume/blob/master/Example/Agrume%20Example/SingleImageViewController.swift

**Comment by meme17sk** [comment]
@JanGorman 

A button is connected to a function that will be called once the button is pressed. The function body contains:

@IBAction func openImage(_ sender: Any) {

{
let argume = Agrume(image: UIImage(named: "my_image")!, background: .blurred(.regular))
agrume.show(from: self)
}
}

The image is shown but it is located on the left, and when i click it will be located correctly on the center.

The image is .png image

**Comment by JanGorman** [comment]
Thanks for the additional detail. That looks like it should work. Could you share:
* iOS version
* iPhone or iPad
* Device in portrait or landscape mode
* The pixel dimensions of the image

I tried a number of combinations (portrait/landscape/square, iPhone/iPad) and they all worked fine. Could you also try to checkout the Agrume project and add the image to the Example project yourself to see if it behaves the same as it does in your project, only to eliminate that option. Thanks

**Comment by meme17sk** [comment]
> Thanks for the additional detail. That looks like it should work. Could you share:
> 
> * iOS version
> * iPhone or iPad
> * Device in portrait or landscape mode
> * The pixel dimensions of the image
> 
> I tried a number of combinations (portrait/landscape/square, iPhone/iPad) and they all worked fine. Could you also try to checkout the Agrume project and add the image to the Example project yourself to see if it behaves the same as it does in your project, only to eliminate that option. Thanks

I'm running my app on: iPhone 11 pro max simulator on Xcode
in portrait position
image Dimensions : 4167 × 4202

**Comment by JanGorman** [comment]
Thanks. So I gave it another try with an image the same size you're using and it looks fine to me. I would suggest to try to isolate the button into a fresh UIViewController with only the button and work backwards from there

![output](https://user-images.githubusercontent.com/138166/107979218-7c036a00-6fbe-11eb-9441-fa65624c9d8b.gif)

**Comment by meme17sk** [comment]
@JanGorman thank you so much 
I really appreciate your help

**Comment by meme17sk** [comment]
I found out the problem

The image was not centered when the app language is not English 
When I set the application language to Arabic, the image is not centered 

But when the app language is English,the image is perfectly showing 

Do you have any idea how to fix this issue?

**Comment by meme17sk** [comment]
@JanGorman please check my last comment 

Thanks

**Comment by JanGorman** [comment]
Thanks @meme17sk – great detective work! I'll take a look with that extra information
