### ISSUE TITLE
Statusbar should be white when viewing images

### ISSUE THREAD

**Issue by MHX792** [JanGorman/Agrume#25]
I have a black text statusbar, which doesn't look good when an image is viewed with Agrume. Disabling or setting the color would solve this problem.

**Comment by JanGorman** [comment]
There's the `public var statusBarStyle: UIStatusBarStyle?` property on an `Agrume` instance which was added recently. It's not document yet though but should cover what you need?

**Comment by MHX792** [comment]
Puurrrfect.
