### ISSUE TITLE
Right / Left swipe should also dismiss the image

### ISSUE THREAD

**Issue by MHX792** [JanGorman/Agrume#27]
I think this would make the user experience better. Right now the angle is too big for dismissing images. You could add an angle propery between 0 and 90° (mirrored on both swipe direction sides).

**Comment by JanGorman** [comment]
Since it's possible to display multiple images, don't you think the left/right swipe to dismiss will interfere with swiping to see other images? PRs welcome however 😉

**Comment by tamoyal** [comment]
i think there could be a single image mode that allows this as in some experiences the user won't expect to be able to see multiple images

**Comment by JoniVR** [comment]
I agree with this, I was wondering why flicking away a single image to the side didn't work. I think the current behavior is great, but when viewing a single image I personally  think it'd be better if the user could also dismiss sideways.

**Comment by JanGorman** [comment]
Ok. Bumping this in the priorities
