### ISSUE TITLE
Globally configure download method

### ISSUE THREAD

**Issue by jakecraige** [JanGorman/Agrume#28]
Right now the download method must be configured on a per instance basis, if I want to use Agrume across my app, I'll need to configure this at every location. 

It would be great if this could be configured somehow that every instance by default uses that, but could be overridden on a per instance basis.

**Comment by JanGorman** [comment]
Right, some kind of service locator. I like the idea

**Comment by JanGorman** [comment]
@jakecraige There's a `AgrumeServiceLocator` that you can use to register a download method – can be overridden on a per instance basis. There's some unit tests that show the usage. Is it what you had in mind?

**Comment by jakecraige** [comment]
Yep that looks great! 

The naming of the method `addDownloadHandler` first made me think it supported multiple download handlers or something, so my only feedback would be to potentially rename that to something like `setDownloadHandler`.

Either way though, thanks for the quick resolution for this!

**Comment by JanGorman** [comment]
Yeah, makes sense to rename. 👍
