### ISSUE TITLE
Create a swift3 branch to merge PR with the newest syntax with Xcode 8 support

### ISSUE THREAD

**Issue by hyouuu** [JanGorman/Agrume#29]
Hi Jan, I made this swift 3 branch in https://github.com/hyouuu/Agrume/tree/swift3, and would like to merge it into a swift3 branch in your repo - could you create one?

Cheers
Shawn

**Comment by JanGorman** [comment]
@hyouuu done: https://github.com/JanGorman/Agrume/tree/swift/3.0
