### ISSUE TITLE
Latest version does not build in Release configuration

### ISSUE THREAD

**Issue by lukeredpath** [JanGorman/Agrume#314]
I'm trying to update our app to use the latest version due to the SwiftyGif fix for #308.

Unfortunately this fails when building for release - the `AgrumeView.swift` file does not compile. I'm not sure why it compiles in Debug but not Release, but as far as I can see the problem is that Agrume still declares support for iOS 9.0 in the Package.swift file but SwiftUI does not exist before iOS 13. If I change this to `.iOS(.v13)` it does compile, with some deprecation warnings.

I'm not sure if you want to drop support for older versions of iOS at this stage, but if you do not then I think the only way around this is to move the SwiftUI support into a separate library/repo with its own Package.swift that specifies iOS 13 minimum.

**Comment by JanGorman** [comment]
I'm OK with dropping iOS 9 support 😅

**Comment by lukeredpath** [comment]
Fixed by #315
