### ISSUE TITLE
Reusing AgrumeViewController instance

### ISSUE THREAD

**Issue by broadwaylamb** [JanGorman/Agrume#33]
When used Swift 2.2 I could once initialize a property `agrume` in my view controller so that when I opened Agrume somewhere inside that view controller via `showFrom(_:)` I could access to that property without instantiating a new Agrume view controller. It used to work well until I migrated to Swift 3 and Xcode 8.

Now when I use this scenario weird things happen, Agrume seems to be shown, but it is invisible (shown in visual debugger though).

BUT when I switched to a different scenario (instantiating a new Agrume view controller), everything worked as expected.

So, the question is, is Agrume designed in a way such that I have to create a new instance every time I want to open it?

**Comment by JanGorman** [comment]
Thanks for reporting this – there's nothing that speaks against having just one instance and re-using that. I will take a look

**Comment by JanGorman** [comment]
Sorry this took so long. The latest commit to the 3.0 branch fixes the issue.
