### ISSUE TITLE
Unknown attribute 'Binding'  pod 5.8.4

### ISSUE THREAD

**Issue by brainfuel** [JanGorman/Agrume#334]
I can run my app with Agrume installed in the simulator and on device just fine. But when I try to archive I get "Unknown attribute 'Binding'" and 20 similar issues.

Target iOS 15
 
Any ideas?

**Comment by JanGorman** [comment]
The `@Binding` is used here [AgrumeView.swift](https://github.com/JanGorman/Agrume/blob/1659fb8a707e075ae6ab8fda3fd89710b46c7208/Agrume/AgrumeView.swift) which correctly imports SwiftUI and has an `@available` annotation… If I had to guess it could be that the `s.platform` in the [podspec](https://github.com/JanGorman/Agrume/blob/master/Agrume.podspec) sets platform to iOS 9 (wow, so old) and that somehow bugs out the compiler.

Could you try forking the library, then set a different value for `s.platform` in the fork and use that fork in your Podfile to see if that resolves the issue?
