### ISSUE TITLE
Variable binding in a condition requires an initializer

### ISSUE THREAD

**Issue by ciathyza** [JanGorman/Agrume#335]
Getting lots of these errors when trying to build example: Variable binding in a condition requires an initializer

**Comment by JanGorman** [comment]
Sorry to hear that. Can you share a screenshot of the errors you're seeing? And which project did you open – the `Agrume.xcworkspace` is the file you should try when running the examples

**Comment by Teglgaard** [comment]
Hi @ciathyza - We are not aware why the error came but were able to fix it by running the most common fix for issues with pods which is in terminal running "pod deintegrate && pod install"

**Comment by Teglgaard** [comment]
Hi again,
We also noticed the bug was persistent on < XCode 14 so make sure to update.

**Comment by JanGorman** [comment]
Ah, the Xcode 14 is a hint then… I recently updated to the newer guard/if let syntax, e.g. here https://github.com/JanGorman/Agrume/commit/cb527996d6f47024c48c4afb80a6db2869556263#diff-917789cb1a7245d59dc362605cc7a664f19ebbca3fdf46ce471380e53a9d6e2aR329

So anything lower than 5.8.5 should work fine with older versions of Xcode
