### ISSUE TITLE
How to use Agrume Offline with SDWebImage

### ISSUE THREAD

**Issue by unittesting0** [JanGorman/Agrume#35]
How to use Agrume Offline with SDWebImage

**Comment by JanGorman** [comment]
The README section [Custom Download Handler](https://github.com/JanGorman/Agrume#custom-download-handler) outlines a way. You can set a global handler through `AgrumeServiceLocator.shared.setDownloadHandler` – doesn't matter what library/code you use here as long as it calls the completion with a `UIImage` in it you're good to go.
