### ISSUE TITLE
'ImageAnalysisInteraction' is only available in Mac Catalyst 17.0 or newer

### ISSUE THREAD

**Issue by willm132** [JanGorman/Agrume#360]
![Screenshot 2023-11-22 at 2 52 15 PM](https://github.com/JanGorman/Agrume/assets/47162632/e61e20f6-1f57-4980-89e3-567e43b76ee4)

**Comment by JanGorman** [comment]
Thanks for reporting. My bad for not considering the mac catalyst support.
I pushed a fix and will trigger a new release

**Comment by willm132** [comment]
@JanGorman Is there going to be any support for Mac Catalyst in the future? This works great on iOS, and would love for it to work on Mac devices also.

**Comment by JanGorman** [comment]
@willm132 Actually I never checked on Mac Catalyst and according to the [documentation](https://developer.apple.com/documentation/visionkit/imageanalysisinteraction) it would work with 17+ so the current `!targetEnvironment(macCatalyst)` is a bit crude. I'll reopen the issue and work on a fix (alternatively a PR is always welcome 🤗)

**Comment by JanGorman** [comment]
I published [5.8.9](https://github.com/JanGorman/Agrume/releases/tag/5.8.9) that enables it when running on Mac Catalyst 17+

**Comment by willm132** [comment]
![Screenshot 2023-12-15 at 7 43 07 AM](https://github.com/JanGorman/Agrume/assets/47162632/1b651a39-7d13-4970-bb1c-e7cc39468522)

**Comment by willm132** [comment]
Great to hear Mac Catalyst support is added!

**Comment by JanGorman** [comment]
🙈 My bad, pushed a fix for that. Don't release on a Friday…

**Comment by willm132** [comment]
Haha, it's working great now thanks!
