### ISSUE TITLE
Xcode8 + Carthage + Agrume 3.0

### ISSUE THREAD

**Issue by OmarCaf** [JanGorman/Agrume#38]
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/omarcafini/Documents/Code/Test/Carthage/Checkouts/Agrume/Agrume.xcworkspace -scheme Agrume -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

**Comment by JanGorman** [comment]
Just briefly looked at this: seems like Carthage is building with the incorrect version of Swift here (i.e. not 3.0). And I see support for a `--toolchain` flag was added. But getting rather late here – I can take a closer look tomorrow

**Comment by OmarCaf** [comment]
I've checked but seems not work...

**Comment by OmarCaf** [comment]
Last test I did, with ore into for you @JanGorman I hope can help you:

The following build commands failed:
	CompileSwift normal arm64 /Users/omarcafini/Documents/Code/ksenia-user/Carthage/Checkouts/Agrume/AgrumeTests/AgrumeServiceLocatorTests.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/omarcafini/Documents/Code/ksenia-user/Carthage/Checkouts/Agrume/AgrumeTests/AgrumeServiceLocatorTests.swift:6:18: error: module 'Agrume' was not compiled for testing
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/omarcafini/Documents/Code/ksenia-user/Carthage/Checkouts/Agrume/Agrume.xcworkspace -scheme Agrume -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Users/omarcafini/Documents/Code/ksenia-user/Carthage/Checkouts/Agrume/AgrumeTests/AgrumeServiceLocatorTests.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by JanGorman** [comment]
Can you just verify please that it's building with the correct version of Xcode: What does `xcode-select -p` point to? Previously I had Xcode GM in a separate folder which messed it up. After that it was just a matter of setting a flag to allow building for testing: fixed with 3.0.1.

**Comment by OmarCaf** [comment]
It's ok with the last commit.

Thank you @JanGorman
