### ISSUE TITLE
Bitcode error Swift 3

### ISSUE THREAD

**Issue by HackShitUp** [JanGorman/Agrume#39]
Module compiled with Swift 2.3 cannot be imported in Swift 3.0 in AgrumeServiceLocator.swift

**Comment by JanGorman** [comment]
Hello,

can you provide a bit more context of what you're trying to achieve? And also how you've installed Agrume, (i.e. Carthage, CocoaPods, directly from source?)

Thanks

**Comment by HackShitUp** [comment]
Yea, I manually installed Agrume. But I've figured out that a lot of the things that are messing up the code is the conversion to Swift 3.0 and Xcode 8.0 and iOS 10 itself.
