### ISSUE TITLE
Deterministic progressbar when downloading from url

### ISSUE THREAD

**Issue by neoneye** [JanGorman/Agrume#41]
Agrume is cool. I like the `agrume.showFrom(self)`. Very simple to use.

When downloading bigger images then it may take a long time to download. Here a progressbar would be nice.

Currently there is an indeterministic spinner. Hard to tell if it's stuck or still downloading.

**Comment by JanGorman** [comment]
Right, calls for an `NSProgress` and option to toggle between them
