### ISSUE TITLE
Problem with imageUrls

### ISSUE THREAD

**Issue by mariokovacevic** [JanGorman/Agrume#43]
There is a problem with an array of image urls. The images are not fetched from the internet on didScroll.

**Comment by JanGorman** [comment]
Hello,

if you check the included sample app and specifically `MultipleURLsCollectionViewController` you can verify that it works. If you're running iOS9+ could it be that `NSAppTransportSecurity` is blocking loading of resources?

**Comment by mariokovacevic** [comment]
Here is a modified version of your example. There is a problem with loading image on didScroll. When you press a image on tableview, everything is working fine, but when you swipe it one or two times and if the image is not already downloaded it has a problem downloading it. The loading indicator is vissible and after some time it disappears, but the image is not added on the screen.

`final class MultipleURLsCollectionViewController: UICollectionViewController {

  private let identifier = "Cell"
  
  private let images = [
    URL(string: "http://www.wellnesspetfood.com/blog/wp-content/uploads/2013/09/Akita-Inu-Puppies-Pictures.jpg")!,
    URL(string: "https://vitaminsforpitbulls.com/wp-content/uploads/2013/06/bulldog_puppies.jpg")!,
    URL(string: "http://cf.ltkcdn.net/dogs/images/slide/185062-849x565-beagle-puppy-portrait.jpg")!,
    URL(string: "http://corgiguide.com/wp-content/uploads/2014/07/6342530545_45ec8696c8_z.jpg")!,
    URL(string: "http://www.dogwallpapers.net/wallpapers/dalmatian-puppy-photo.jpg")!,
    URL(string: "https://s-media-cache-ak0.pinimg.com/564x/4d/ac/2d/4dac2d281f68796887efc6d4c71e6864.jpg")!
  ]
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    let layout = collectionView?.collectionViewLayout as! UICollectionViewFlowLayout
    layout.itemSize = CGSize(width: view.bounds.width, height: view.bounds.height)
  }
  
  // MARK: UICollectionViewDataSource
  
  override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
    return images.count
  }
  
  override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    let cell = collectionView.dequeueReusableCell(withReuseIdentifier: identifier, for: indexPath) as! DemoCell
    cell.imageView.image = UIImage(named:"MapleBacon")
    return cell
  }
  
  // MARK: UICollectionViewDelegate
  
  override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
    let agrume = Agrume(imageUrls: self.images, startIndex: indexPath.row, backgroundBlurStyle: .dark)
    agrume.didScroll = { [unowned self] index in
      self.collectionView?.scrollToItem(at: IndexPath(row: index, section: 0), at: [], animated: false)
    }
    agrume.showFrom(self)
  }
}
`

**Comment by JanGorman** [comment]
It's the app transport security as I suspected. If you're running this code in the example app as you posted it, you'll notice in the console messages like:

```
 App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
```

The example doesn't have that setting enabled since the example URLs all are https so no need. What you'll need to do in the sample is edit the Info.plist file to allow arbitrary loads:

<img width="585" alt="screen shot 2016-10-15 at 09 46 11" src="https://cloud.githubusercontent.com/assets/138166/19408398/48d21520-92bc-11e6-9361-5dbab2eee10b.png">

And you'll have lovely dog pictures:

![screen shot 2016-10-15 at 09 47 21](https://cloud.githubusercontent.com/assets/138166/19408404/683448a2-92bc-11e6-8843-3c23d22952e9.png)

**Comment by JanGorman** [comment]
@mariokovacevic Does the ATS change fix your issue? If so I'd close the ticket.

**Comment by mariokovacevic** [comment]
No, App Transport Security was already added, issue is still there. Open the first image, this is successful, then swipe to next image, you will notice that it is downloading too long and in most cases it can't finish. The loader stops and disappears but there is no image.

**Comment by JanGorman** [comment]
Ok odd, I didn't have that problem. All images loaded fine. This is going to be a bit hard to debug that way 😅

**Comment by mariokovacevic** [comment]
I will try to find a solution or workaround when I find enough free time and send you. It's a good library. Thanks

**Comment by agirolami87** [comment]
Hi,
I have the same problem. I use a collectionview and when I pass the urls of images to Agrume the second image never loads.
This is the code:
`    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let URLs = photos.map { URL(string:$0.photoUrl!) }
        let agrume = Agrume(imageUrls: URLs as! [URL], startIndex: indexPath.row, backgroundBlurStyle: .dark)
        agrume.didScroll = { [unowned self] index in
            self.collectionView?.scrollToItem(at: IndexPath(row: index, section: 0), at: [], animated: true)
        }
        agrume.showFrom(self)
    }
`

I have also included video to see that
[test.mov.zip](https://github.com/JanGorman/Agrume/files/966271/test.mov.zip)

**Comment by JanGorman** [comment]
@agirolami87 Code looks fine of course – it'd be interesting to see what you see when you put a breakpoint in `ImageDownloader` on line 23 where the optional unwrap of download image data happens. Does it successfully pass that point, can it turn the data into a `UIImage`?

**Comment by agirolami87** [comment]
it pass that point and turn the data into a `UIImage` but does't show image.

**Comment by JanGorman** [comment]
@agirolami87 Can you share the image urls please? I'll try and reproduce

**Comment by agirolami87** [comment]
`[”https://firebasestorage.googleapis.com/v0/b/montesole-app-b222c.appspot.com/o/foto%2FMonte%20Caprara%2FMonte%20Caprara%20001.jpg?alt=media&token=4c313da6-c11f-44da-8c65-ad75cc6ee58f”,	
”https://firebasestorage.googleapis.com/v0/b/montesole-app-b222c.appspot.com/o/foto%2FMonte%20Caprara%2FMonte%20Caprara%20002.jpg?alt=media&token=38bed215-f7b2-41e4-b132-2c9ea4dae15d”,	
”https://firebasestorage.googleapis.com/v0/b/montesole-app-b222c.appspot.com/o/foto%2FMonte%20Caprara%2FMonte%20Caprara%20003.jpg?alt=media&token=92ed40ed-722e-4f8f-b810-c52dad4bb077”,	
”https://firebasestorage.googleapis.com/v0/b/montesole-app-b222c.appspot.com/o/foto%2FMonte%20Caprara%2FMonte%20Caprara%20004.jpg?alt=media&token=971e5d7f-5fdb-4b59-b50c-85a6ae49fd61”,
”https://firebasestorage.googleapis.com/v0/b/montesole-app-b222c.appspot.com/o/foto%2FMonte%20Caprara%2FMonte%20Caprara%20005.jpg?alt=media&token=48cdfb86-ef54-4d4f-a252-b89638bcfcd7”]`

**Comment by JanGorman** [comment]
@agirolami87 I was able to reproduce. The issue was that dequeuing cells cancelled previous image downloads. I believe this has to do with the changed cell dequeuing since iOS 10 which prepares multiple cells at once. So the third cell dequeued you don't see yet cancelled the image download of the second one on screen.

**Comment by agirolami87** [comment]
Thanks a lot, now works well!
