### ISSUE TITLE
Example using AgrumeServiceLocator.shared.setDownloadHandler

### ISSUE THREAD

**Issue by LarsWith** [JanGorman/Agrume#45]
Is there any example using:

```
AgrumeServiceLocator.shared.setDownloadHandler { url, completion in

}
```

I would like to use [Kingfisher](https://github.com/onevcat/Kingfisher) to download and cache images in a `UICollectionView` slider

**Comment by JanGorman** [comment]
I have no experience with that library but a look at the wiki page suggests to me something like this should work:

```swift
AgrumeServiceLocator.shared.setDownloadHandler { url, completion in
  ImageDownloader.default.downloadImage(with: url, options: [], progressBlock: nil) { image, error, _, _ in
    // Do some checks that image != nil, error != nil maybe
    completion(image)
  }
}
```

The download handler is called with the required URL and a completion black that takes the image that you download by some other means.

**Comment by kiwo12345** [comment]
@JanGorman this is how I download/cache an image using Kingfisher

```
let url = URL(string: "https://domain.com/image.jpg")!
imageView.kf.setImage(with: url)
```

I am just not sure how I should place it in the `AgrumeServiceLocator.shared.setDownloadHandler`

**Comment by JanGorman** [comment]
Yeah right, that won't work because it doesn't expose the `UIImageView`. But you do have access to the `ImageDownloader` that it uses internally: https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-imagedownloader-to-download-an-image-without-caching

So the snippet that I posted above should do the trick. Take note though that this then doesn't cache and you'd need to handle that yourself. Kingfisher also exposes it's internal cache, so something like

```swift
AgrumeServiceLocator.shared.setDownloadHandler { url, completion in
  let key = "" // Hash the url you're passed here and use that as you'r cache key
  ImageCache.default.retrieveImage(forKey: key, options: nil) { image, _ in
    if let image = image {
      completion(image) // Call the completion that Agrume passes you with the image from cache
    } else {
      ImageDownloader.default.downloadImage(with: url, options: [], progressBlock: nil) { image, error, _, _ in
      ImageCache.default.store(image, forKey: key) // Uses the same key you created above, next time should hit the cache then
    completion(image)  // Call the completion that Agrume passes you with the image you downloaded
  }
    }
  }
}
```

something like that.

**Comment by kiwo12345** [comment]
@JanGorman big thanks!!
