### ISSUE TITLE
Double Tap Zoom Problems

### ISSUE THREAD

**Issue by DavidLari** [JanGorman/Agrume#48]
Hi,
I notice that depending on the image, when I double tap to zoom, sometimes the whole image scrolls off the screen when it zooms in. For example,  a wide image on a device in portrait orientation is one situation.

In looking at the func doubleTap in AgrumeCell.swift to examine the problem, I notice some code computing targetZoom that appears inconsistent and I believe this is the cause of the problems.

For example, you're using the zoomWidth in a calculation for height. And you are doing division rather than subtraction in another part. Not sure which is correct, but they are inconsistent. Also, the *else* part has the same inconsistent code. 

I have been experimenting with changing this code around and have made a version that appears to function a little better than what's in the repo, but as I don't fully understand what the code is trying to do, it would probably be better if the author looked at making fixes.

**Comment by DavidLari** [comment]
Here's the code I'm using now and it seems to be working pretty well.

```
    if notZoomed() {
      let zoomWidth = contentView.bounds.width / AgrumeCell.targetZoomForDoubleTap
      let zoomHeight = contentView.bounds.height / AgrumeCell.targetZoomForDoubleTap
      targetZoom = CGRect(x: point.x - zoomWidth / 2, y: point.y - zoomHeight / 2, width: zoomWidth, height: zoomHeight)
      targetInsets = contentInsetForScrollView(atScale: AgrumeCell.targetZoomForDoubleTap)
    } else {
      let zoomWidth = contentView.bounds.width * scrollView.zoomScale
      let zoomHeight = contentView.bounds.height * scrollView.zoomScale
      targetZoom = CGRect(x: 0, y: 0, width: zoomWidth, height: zoomHeight)
      targetInsets = contentInsetForScrollView(atScale: 1)
    }
```

**Comment by JanGorman** [comment]
Thanks for reporting. I have some spare time next week to dig into this.

**Comment by JanGorman** [comment]
@DavidLari p.s. do you have a wide image where you noticed this and that I can use as a sample?

**Comment by DavidLari** [comment]
Here's a link to a page with a wide image on a free stock photo web site. 
https://www.pexels.com/photo/person-standing-on-gray-path-way-near-bicycles-during-night-time-175032/

**Comment by JanGorman** [comment]
@DavidLari I just pushed `3.0.4`. Could you verify that this fixes the issue for you? Cleaned it up a bit and indeed zooming out to `CGPoint.zero` at a scale of 1 should do the trick. 🤞

**Comment by DavidLari** [comment]
Just tested it out and looks good. Thanks!

**Comment by JanGorman** [comment]
Great to hear. Thanks for reporting!
