### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by kristokiis** [JanGorman/Agrume#49]
Seems when orientated to landscape view does some extra transformation and rotates 180 degrees instead of 90 degress. Picture gets orientated as should, but with weird animation.

**Comment by musbaalbaki** [comment]
+1

**Comment by Alexookah** [comment]
+1

**Comment by JanGorman** [comment]
Interesting. I could see how this was an issue in older versions that were generating orientation change notifications and doing this "manually" but the latest one relies on the system to handle it.

**Comment by Alexookah** [comment]
the orientation doesnt update correctly when you initialise Agrume on landscape.
(when you rotate the device part of the image is cropped)
(tested on iphone x)

**Comment by Alexookah** [comment]
@JanGorman 
This issue should be closed now i think

**Comment by JanGorman** [comment]
Agreed. Thanks for all your PRs!
