### ISSUE TITLE
Show picture animation flickers

### ISSUE THREAD

**Issue by hyouuu** [JanGorman/Agrume#5]
Thanks for the component! When i call showFrom() it flickers badly, and seems to be caused by collectionView.transform parts - have you experienced similar issues?

**Comment by JanGorman** [comment]
@hyouuu are you opening a single image or a collection of images? If you could give some sample code to reproduce that'd be much appreciated. Thanks!

**Comment by hyouuu** [comment]
Hi Jan I was just opening a single image, but a collection shows the same effect. The sample code is just straightforward from the instruction:
let agrume = Agrume(image: image)
agrume.showFrom(self)

And it has the same effect on iOS 8.4 simulator and iOS 9 beta 5 on device. Haven't you seen similar issues? It was built on Xcode 6.4

**Comment by hyouuu** [comment]
Not sure if you are still maintaining this, but if so I've found the cause of the issue - we should set the alpha to 0 before calling presentViewController.

A proposed updated showFrom function:

public func showFrom(viewController: UIViewController) {
    backgroundSnapshot = UIApplication.sharedApplication().delegate?.window??.rootViewController?.view.snapshot()

    view.userInteractionEnabled = false
    initialOrientation = UIApplication.sharedApplication().statusBarOrientation

    dispatch_async(dispatch_get_main_queue()) {
      self.collectionView.alpha = 0
      self.collectionView.frame = self.view.bounds
      let scaling = CGFloat(0.6)
      self.collectionView.transform = CGAffineTransformMakeScale(scaling, scaling)

      viewController.presentViewController(self, animated: false) {

        UIView.animateWithDuration(Agrume.TransitionAnimationDuration,
          delay: 0,
          options: [.BeginFromCurrentState, .CurveEaseInOut],
          animations: {
            [weak self] in
            self?.collectionView.alpha = 1
            self?.collectionView.transform = CGAffineTransformIdentity
          },
          completion: {
            [weak self] finished in
            self?.view.userInteractionEnabled = finished
          }
        )
      }
    }
  }

**Comment by JanGorman** [comment]
@hyouuu Thanks for the update; still maintaining, just wasn't able to follow along what you meant at the time. Could you do a fork and open a pull request please then with your suggested change and I can merge it in.

**Comment by hyouuu** [comment]
Sorry it's kind of hard to describe, and I put more detail in the pull request: https://github.com/JanGorman/Agrume/pull/7

**Comment by JanGorman** [comment]
Fixed with #7
