### ISSUE TITLE
Flicker after closing the expanded image

### ISSUE THREAD

**Issue by nevinjethmalani** [JanGorman/Agrume#51]
Really love this library! I am having a small issue when closing images. Would love to get your thoughts on what the issue might be.

I get a little flicker after the image I tap is closed. I have included a video here. 

The image is in a scrollview. 
[Untitled.zip](https://github.com/JanGorman/Agrume/files/963187/Untitled.zip)

**Comment by JanGorman** [comment]
Thanks for the report! I'm snowed under with work at the moment but I should get a chance to look at it sometime this weekend. I'll keep you posted.

**Comment by nevinjethmalani** [comment]
Perfect. Thaks a lot! You can download our app here to see where it is happening: http://www.shoplooq.com/

I have also included a video with slowed animations and it shows that the view is expanding outside of the screen and pushing even the content above it up. I have also included screenshots to see what content is being expanded. Hope that helps!
[Archive 3.zip](https://github.com/JanGorman/Agrume/files/965104/Archive.3.zip)

**Comment by JanGorman** [comment]
I'm having a hard time reproducing this myself but I do suspect that there is an issue with the background snapshot the lib captures to fade out nicely (or blur) when it's dismissing. Would it be possible for you to call the `showFrom` method not only with the viewController it's presenting from but also with the optional `backgroundSnapshotVC` parameter. Set that parameter to the absolute root of your view hierarchy. Does that fix the issue?
In case it does, it'd be interesting to see what's the difference between what you pass as root and what the `fileprivate func viewControllerForSnapshot(fromViewController:)` method comes up with. If you could breakpoint that and check the difference if any…

**Comment by nevinjethmalani** [comment]
That did not fix the issue. If we set it to self, it does the same thing. Here I set it to the rootVC. and below I have set it to self which is the root VC. This code is executed when the button over the image is tapped.
 
`let agrume = Agrume(image: mainImageForFull, backgroundColor: .black)
        agrume.hideStatusBar = true
        var window :UIWindow = UIApplication.shared.keyWindow!
        let root = window.rootViewController
        agrume.showFrom(self, backgroundSnapshotVC: root)`


`let agrume = Agrume(image: mainImageForFull, backgroundColor: .black)
        agrume.hideStatusBar = true
        agrume.showFrom(self, backgroundSnapshotVC: self)`

**Comment by nevinjethmalani** [comment]
We are using a sticky header for the image view so that is most likely the reason for the issue. Does Agrume adjust any scroll view properties (i.e. offset) or the location of any objects in the view?

**Comment by JanGorman** [comment]
Sorry for the delay, I'm in the middle of an app release atm so everything is a bit hectic 🙃.

To answer your question, Argue doesn't adjust any scroll view properties and doesn't do anything at all to the controller that's presenting, it only uses it to present from.
If possible, could you comment out line 243 (`backgroundSnapshot = …`) in the `showFrom` method and check if you still see the flickering then? It won't fade out as smoothly but at least then we'd know for sure if it is an issue with the snapshot Agrume takes or something in your view.

**Comment by nevinjethmalani** [comment]
Completely understand! I just tried commenting out that line and it does not change anything. It looks like it is something else that is getting moved around.

**Comment by tomykho** [comment]
+1 same for me

**Comment by nevinjethmalani** [comment]
Perfect. Glad to know that it is not just me. @tomykho can you give a little more insight on how you are implementing Agrume? 

@JanGorman We have other pages being dismissed from that VC and I checked the code in our ViewDidAppear of the VC that we are using Agrume in and I don't think it is anything like that.

**Comment by nevinjethmalani** [comment]
Hey, I wanted to quickly follow up to see if you were able to reproduce the issue. Let me know if you have any questions.

**Comment by JanGorman** [comment]
Hey Nevin – I haven't had a chance yet, sorry. But also haven't forgotten about it ;)

**Comment by JanGorman** [comment]
@nevinjethmalani you mentioned a sticky header on the image view. Are you referring to `sectionHeadersPinToVisibleBounds = true` or something else?

**Comment by nevinjethmalani** [comment]
No we aren't using a table view or a collection view to create the sticky header. We are doing it in the story board using constraints. It is a little difficult to explain the exact way the constraints are laid out. 

If I am not mistaken, when I get rid of the animation in your project, the issue does not exist.

**Comment by musbaalbaki** [comment]
I have the same issue especially when using backgroundColor or backgroundBlurStyle, agrume change my underneeth tableview scroll offset. It works fine though when not using backgroundColor or backgroundBlurStyle

**Comment by JanGorman** [comment]
Thanks @musbaalbaki for the info. This kind of reaffirms that I think it's an issue with the screenshot that is captured and used to blur (and is also captured when using a background color). As you can see https://github.com/JanGorman/Agrume/blob/master/Agrume/Agrume.swift#L272 all that the library does is call `viewController.present(…)`.
I wasn't able to reproduce it at the time. Would you be able to share your code so that I can investigate further?

**Comment by nevinjethmalani** [comment]
I believe the scrollview that the image is displayed in scrolls up and down by 20 points when the flicker happens if that helps. @musbaalbaki, is yours in a scrollview?

**Comment by Alexookah** [comment]
I dont think this issue any loger exists in the current release.
@JanGorman maybe this issue should be closed and re-open if someone experiences something similar to this?

**Comment by JanGorman** [comment]
Thanks for raising this. Agreed that this can be closed

**Comment by Alexookah** [comment]
@JanGorman 
I have a feeling this could have been related to my issue:
https://github.com/JanGorman/Agrume/issues/96
