### ISSUE TITLE
Rotation improvement

### ISSUE THREAD

**Issue by walsht** [JanGorman/Agrume#59]
When rotating the image the animation is not fluid the image snaps into place... can this be improved?

**Comment by JanGorman** [comment]
It animates the layout changes alongside `UIViewControllerTransitionCoordinator` but I definitely see what you mean.

**Comment by allaire** [comment]
@JanGorman My app doesn't support rotation, but when I rotate it and open an image via Agrume, the image is out of place. Do you think it would be possible to check if the app support device orientation before listening to orientation change?

**Comment by JanGorman** [comment]
@allaire Sounds like the sane thing to do 😄 I created #74 to track this

**Comment by UtkuDalmaz** [comment]
Any improvement on this?

**Comment by JanGorman** [comment]
@UtkuDalmaz Fixed with 5.x. I forgot to update the issue status.
