### ISSUE TITLE
Rare crash on index out of bound

### ISSUE THREAD

**Issue by hyouuu** [JanGorman/Agrume#65]
I couldn't reproduce it but there are always a few reports about this crash. Here is my code to use agrume, and I verified the startIdx < imageUrls.count:

```
      agrume = Agrume(
            imageUrls: imageUrls,
            startIndex: startIdx,
            backgroundColor: .black)
        isPresentingAView = true
        agrume?.hideStatusBar = true
        agrume?.showFrom(self)
```

Here is the crash stacktrace:

```
Fatal Exception: NSInvalidArgumentExceptionattempt to scroll to invalid index path: <NSIndexPath: 0x1d04369c0> {length = 2, path = 0 - 3} Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
4 | UIKit | -[UICollectionView _scrollToItemAtIndexPath:atScrollPosition:animated:]
5 | Agrume | Agrume.swift line 259Agrume.addSubviews() -> ()
6 | Agrume | Agrume.swift line 237Agrume.showFrom(UIViewController, backgroundSnapshotVC : UIViewController?) -> ()
```

Any thoughts on it? Even if the startIdx is out of bound we should do a check before addSubviews - I'll also see if I could make a PR for this

**Comment by JanGorman** [comment]
Hey there,

Thanks for the report. Indeed nothing obvious in the code stands out. In the specific call the only thing I updated with #66 just now was the incorrect use of `row` vs. `item` in constructing the `IndexPath`. 🤷‍♀️ I'll push a release

**Comment by hyouuu** [comment]
Haha cool I'll close for now and if in the next version it happens again then re-open. Thanks!
