### ISSUE TITLE
Background does not blur

### ISSUE THREAD

**Issue by Eric0625** [JanGorman/Agrume#67]
When I start the agrume instance, the background is not blurred. Any clue about this? The code is exactly the same as the example

**Comment by JanGorman** [comment]
Hi @Eric0625 ,

per default it'll use `UIBlurEffectStyle.light` – which on a light background isn't very pronounced, you can change to a dark one with `Agrume(image: …, backgroundBlurStyle: .dark)`

Otherwise if you have a screenshot that'd be helpful if there is an issue.

**Comment by Eric0625** [comment]
It worked! Thanks! Here is the screenshot before altering the style, you can see the background is fairly clear.

![screen shot 2017-11-14 at 11 34 23 am](https://user-images.githubusercontent.com/18132007/32815661-1603f08e-c9f0-11e7-99b4-2d4ba85e694c.png)
