### ISSUE TITLE
Swipe left/right to close with multiple images?

### ISSUE THREAD

**Issue by jmeyers91** [JanGorman/Agrume#68]
If I use `Agrume` to display a list of URLs and swipe to the last image, I can't swipe (right to left) again to close it, but if the list only contains a single URL, I can swipe left/right to close the single image. Is there any way to enable this functionality when displaying more than one image?

**Comment by JanGorman** [comment]
Hi James,

There currently is no such option. If I get you right, you'd want the first/last image of a collection to be dismissible via a swipe to the side?

**Comment by jmeyers91** [comment]
Yes that's what I was looking for.

**Comment by JanGorman** [comment]
Ok, I'll see what I can do then :)

**Comment by Alexookah** [comment]
Using withPhysicsAndButton is possible to dismiss any image from the list of URLS
Close this issue @JanGorman
