### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by MobileMon** [JanGorman/Agrume#75]
Seeing a massive amount of memory leaks when using Argume in both the example project and my own personal project

In particular they occur when showing an image:     agrume.showFrom(self)

In the example app if I click on "Multiple Images", then click on an image, this will trigger it

**Comment by JanGorman** [comment]
![screen shot 2018-02-19 at 16 34 15](https://user-images.githubusercontent.com/138166/36385422-cce16514-1592-11e8-8e98-a96c461e921f.png)

I see that it's using memory (as is to be expected) but it's also being released again. I also quickly checked the memory graph debugger but don't see any sign of cycles there.

Can you provide further details that lead you to believe that it is leaking memory?

**Comment by MobileMon** [comment]
Profile the example app and run the "leaks" program in instruments

Goto "Multiple Images" in the tableview

Click on a image to expand it

See this screenshot:

 
![screen shot 2018-02-19 at 12 08 59 pm](https://user-images.githubusercontent.com/2768159/36389621-b471159e-156d-11e8-8dd8-2491397bb4bb.png)

**Comment by JanGorman** [comment]
Thanks for the report. This was so minor that it's not really noticeable in the regular memory view but I was able to reproduce it. The cells use a [UIDynamicAnimator](https://developer.apple.com/documentation/uikit/uidynamicanimator) for the flick to dismiss which looks like it's retaining its `referenceView`. Unfortunately not documented
