### ISSUE TITLE
GIF support?

### ISSUE THREAD

**Issue by allaire** [JanGorman/Agrume#76]
It would be nice to support Animated Gifs. Maybe using a UIImage/UIImageView extension to support it? I also stumbled upon https://github.com/kirualex/SwiftyGif

Thanks!

**Comment by JanGorman** [comment]
Yes agreed. I even wrote my own unpopular library a couple of years ago https://github.com/JanGorman/Zoetrope 😆 

I've come across SwiftGif as well, it looks good.

There's a number of features now already in the pipeline which I want to tackle during some vacation days I have next week, gif support just made the list.

**Comment by allaire** [comment]
@JanGorman Awesome! Just wondering, is there an easy way to use this with a UIImage that was pulled online? I tried this but it didn't work:

```swift
            guard var image = viewModel.originalImage ?? viewModel.image.value else { return }
            
            let isGIF = viewModel.originalImageUrl?.contains(".gif") ?? false
            
            if let imageData = image.imageData, isGIF {
                image = UIImage(gifData: imageData)
            }
            
            let agrume = Agrume(image: image, background: .blurred(.dark))
            agrume.show(from: topViewController)
```

**Comment by allaire** [comment]
@JanGorman Yes exactly, already passed as a UIImage. Strangely I got it to work by using this lib: https://github.com/swiftgif/SwiftGif

I suppose there still a way to access the GIF source somehow?

**Comment by allaire** [comment]
@JanGorman Great, I got it to work by keeping the original image data, thanks!

**Comment by JanGorman** [comment]
That's the library I ended up using was well. And just saw the comment as I was about to write… great! 😃
