### ISSUE TITLE
Add the option to add Custom Buttons like Close and Share

### ISSUE THREAD

**Issue by Daxito** [JanGorman/Agrume#79]
It would be nice if there was someway of adding custom buttons to the preview image, like an X to close and a button to share the Image (eg Email it)

Thanks!

**Comment by Daxito** [comment]
Hey! Just checking if this would be possible, I have dumb users that don't know how to close an image and are expecting an "X" button at the top just like their FaceBook App....

Thanks!

**Comment by JanGorman** [comment]
Yes, certainly possible. I don't want to make a promise I won't be able to keep but I put on my TODO list now for this coming weekend. 🤞

**Comment by Daxito** [comment]
@JanGorman Thank you!!!
