### ISSUE TITLE
Any plans to add captions?

### ISSUE THREAD

**Issue by kenrickvaz** [JanGorman/Agrume#8]
Firstly thank you very much for such an excellent library! Absolutely love it!

Do you have plans to add captions for photos?

**Comment by JanGorman** [comment]
Hi – certainly a good idea, pull requests are always wellcome :trollface: I'll look into it when I have some time.

**Comment by neoneye** [comment]
Agrume to show captions in top/bottom, such as file size, image resolution, file name. Preferably texts that can be assigned after the image has finished downloaded. The captions can be provided by the server along with the downloaded image.

**Comment by JanGorman** [comment]
#154 Adds an option for custom overlay views. Internally Agrume uses a wrapper struct that could include a title. Not exposed publicly yet but the plumbing is in place now
