### ISSUE TITLE
Having error after the last update

### ISSUE THREAD

**Issue by UtkuDalmaz** [JanGorman/Agrume#85]
I am having this error after the last update

<img width="969" alt="screen shot 2018-05-07 at 16 22 06" src="https://user-images.githubusercontent.com/2130592/39704067-e824da2e-5212-11e8-97c5-595d2e43b9cf.png">

**Comment by JanGorman** [comment]
Hi there. As it was a major update (going from 4.x to 5.x) I took the liberty of changing the API a little; for your specific case the call would look like this now:
```swift
let agrume = Agrume(images: images, startIndex: indexPath.item, background: .blurred(.light))
```
The background now is an enum with associated value, either of type `blurred(UIBlurEffectStyle)` or `.colored(UIColor)` which simplified the implementation _a lot_ and makes for a cleaner API.

I will write a migration guide in the wiki to highlight the changes.

**Comment by UtkuDalmaz** [comment]
I am now having this error
`Cannot convert value of type '[URL]' to expected argument type '[UIImage]'`

**Comment by JanGorman** [comment]
mh yes, I was wondering a bit about the name of the variable in your screenshot. I was certain that the parameter name for multiple URLs was `imageUrls` so didn't ask further. 😄  Anyway, to fix it:
```swift
let agrume = Agrume(urls: URLs, …)
```

**Comment by JanGorman** [comment]
And I see how that part of the README can be confusing. I'll update that

**Comment by UtkuDalmaz** [comment]
A question man.
Is there any closure handler so I can execute code when image library closed?
