### ISSUE TITLE
Animated GIF not animating when tapping on image

### ISSUE THREAD

**Issue by walsht** [JanGorman/Agrume#87]
I am setting the gif image like this:
 `setGifImage(UIImage(gifData: data))`
It is animating fine, but when tapping on it 
`agrume.show(from:controller)`
it just gives me the image and doesn't animate.

Is this expected?  I would assume it would animate.

**Comment by JanGorman** [comment]
It should animate, yes. Can you show the line that you use to initialise Agrume? As discussed here #76 yesterday Agrume needs the image passed in as an instance created using the `UIImage(gifName:)` or `UIImage(gifData:)` initialiser or otherwise the gif information is already lost

**Comment by walsht** [comment]
Here you go, I am using this within a custom UIImageView, so I just get the self.image, do I have to pass in UIImage(gifData: data)?

`    func imageTapped(sender : UITapGestureRecognizer) {
        guard let image = image, let controller = tapToDetailPresentingController else { return }
        let agrume = Agrume(image: image, background: .blurred(.dark))
        agrume.statusBarStyle = .lightContent
        agrume.hideStatusBar = ImageView.appearance().hideStatusBar
        agrume.show(from:controller)
    }`

**Comment by walsht** [comment]
I think I got it... using UIImage(gifData:) vs self.image works.  Thanks.

**Comment by JanGorman** [comment]
Great! If you have any suggestions for improving documentation please don't hesitate to let me know.

**Comment by walsht** [comment]
I don't have time to make a PR, but this might help.
![screen shot 2018-05-11 at 2 58 32 pm](https://user-images.githubusercontent.com/1455799/39944323-dba699c4-552b-11e8-8171-ccb250b19dbe.png)
