### ISSUE TITLE
Custom data source problem

### ISSUE THREAD

**Issue by mdilaveroglu** [JanGorman/Agrume#88]
Hello, 

I am trying to use custom data source for loading images from photo library. Here is my data source implementation: 

```
class AssetDataSource: AgrumeDataSource {

    var numberOfImages: Int
    var urls: [URL]

    init(urls: [URL]) {
        self.urls = urls
        self.numberOfImages = urls.count
    }

    func image(forIndex index: Int, completion: @escaping (UIImage?) -> Void) {
        let assets = PHAsset.fetchAssets(withALAssetURLs: urls, options: nil)

        let imageManager = PHCachingImageManager()
        let imageRequestOptions = PHImageRequestOptions()
        imageRequestOptions.isNetworkAccessAllowed = true
        imageRequestOptions.isSynchronous = true

        imageManager.requestImage(for: assets[index], targetSize: PHImageManagerMaximumSize, contentMode: .aspectFill, options: imageRequestOptions) { image, _ in
            completion(image)
        }
    }

}
```

And I'm using it like this:

```
let dataSource: AgrumeDataSource = AssetDataSource(urls: imageUrls)
let agrume = Agrume(dataSource: dataSource, startIndex: index, background: .blurred(.light))
agrume.show(from: self)
```

But it falls into an infinite loop in this init function.

```
public convenience init(dataSource: AgrumeDataSource, startIndex: Int = 0, background: Background = .colored(.black)) {
     self.init(dataSource: dataSource, startIndex: startIndex, background: background)
}
```

Is this the right way to use Custom Data Source? Or is this a bug with library?
Thank you in advance.

**Comment by JanGorman** [comment]
Hi – that indeed is a bug then 😣.

**Comment by JanGorman** [comment]
I just published [5.0.3](https://github.com/JanGorman/Agrume/releases/tag/5.0.3) that fixes the issue. Thanks for reporting!

**Comment by mdilaveroglu** [comment]
Hey @JanGorman thanks for the fix. 
There is one more thing. I tried it after now and noticed something. `dataSource` would not get set even if it is created correctly. Resulting `imageForIndex` method to not get called. 

Making the `dataSource` variable strong fixed it for me.

**Comment by mdilaveroglu** [comment]
@JanGorman any update on this?

**Comment by JanGorman** [comment]
Hi,
Sorry I assumed that retaining the `dataSource` yourself was ok (yes, this is the correct approach 😬).

So I see that either a) I need to update the documentation to make that explicit or b) internally wrap the `dataSource` inside of a  "Trampoline" class that's weakly retained. The reason why `dataSource` is weak in the first place, is that if you don't supply a custom one, Agrume will be it's own `dataSource` which simplifies the implementation and also prevents bugs by ensuring that the protocol stays in sync with the rest of the library.

Thoughts?

**Comment by mdilaveroglu** [comment]
Hey,

I think just updating the documentation kinda breaks the point of having custom data source in the library. Because now, the only way to work with a custom data source is forking and changing the code.

 I am also wondering that if I am the only one using a custom data source 😄. 

Anyways thank you for work.

**Comment by JanGorman** [comment]
Ah sorry, then I missed your point completely. I thought what you were doing is something like

```swift
class MyViewController: UIViewController {

  private let dataSource = AgrumeDataSource()
  private lazy var agrume: Agrume = {
    return Agrume(dataSource: dataSource)
  }()

}
```

So retaining the data source in your own class. That should work, no?

**Comment by mdilaveroglu** [comment]
Yes retaining the data source in my class worked perfectly. Thank you for your help.
