### ISSUE TITLE
App crashes when scrolling the collectionview

### ISSUE THREAD

**Issue by UtkuDalmaz** [JanGorman/Agrume#89]
Hi,

I am using agrume 5.0.2 
Agrume makes the app crashes when I scroll down the collectionview.

Here is my code,
```
override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        
        let URLs = images.map { $0 }
        
        let agrume = Agrume(urls: URLs, startIndex: indexPath.item, background: .blurred(.light))
        agrume.didScroll = { [unowned self] index in
            self.collectionView?.scrollToItem(at: IndexPath(item: index, section: 0), at: [], animated: false)
        }
        agrume.didDismiss = {
           NotificationCenter.default.post(name: Notification.Name(rawValue: "showCenterButton"), object: nil)
        }
        agrume.show(from: self)
    }
```

Please investigate

**Comment by JanGorman** [comment]
Do you have a stack trace to share?

**Comment by UtkuDalmaz** [comment]
It just says “Terminating due to memory issue” on xcode

Utku Dalmaz (DLMZ)
Tel: +905334373245

LinkedIn: http://tr.linkedin.com/pub/utku-dalmaz/34/773/811
Youtube: http://youtube.com/utkudalmaz
Facebook: http://facebook.com/utkudalmaz
Soundcloud: http://soundcloud.com/utkudalmaz
Skype: utkudalmaz

**Comment by JanGorman** [comment]
I would need more than that to go on. Out of curiosity, how many images are you displaying there… are they particularly large? Does it still crash when you comment out this code to be sure that the bug is triggered by the library and not your own code

```swift
agrume.didScroll = { [unowned self] index in
            self.collectionView?.scrollToItem(at: IndexPath(item: index, section: 0), at: [], animated: false)
        }
```

**Comment by UtkuDalmaz** [comment]
Sorry The problem was about SDWebImage.
