### ISSUE TITLE
Type 'AgrumeImage' does not conform to protocol 'Equatable'

### ISSUE THREAD

**Issue by hemangshah** [JanGorman/Agrume#91]
**Problem**:

<img width="1052" alt="screen shot 2018-09-06 at 10 24 12 am" src="https://user-images.githubusercontent.com/3313412/45135833-096fec80-b1bf-11e8-9cef-a582906d5375.png">

**Solution**:

Implementing below function

```
    public static func ==(lhs: AgrumeImage, rhs: AgrumeImage) -> Bool {
        
    }
```

V. 5.0.1

If you can update this and release a new version.

**Comment by JanGorman** [comment]
Which version of Swift are you using? Swift 4.1 introduced synthesized equatable conformance

**Comment by hemangshah** [comment]
Oh okay! I am using 4.0
