### ISSUE TITLE
 landscape iphone X layout issue

### ISSUE THREAD

**Issue by Alexookah** [JanGorman/Agrume#96]
when showing agrume in landscape mode using iphone X.
the image is not shown in center.
![screen shot 2018-10-08 at 11 12 51](https://user-images.githubusercontent.com/9624843/46598007-20ba3680-caeb-11e8-8fbc-cfc886ae4e54.png)

**Comment by sschizas** [comment]
@JanGorman any update on this issue?

**Comment by psoilemezis** [comment]
@JanGorman same happens on iPhone 8 iOS 12.2

**Comment by JanGorman** [comment]
Thanks for the push. PRs are always welcome 😬 

_Might_ have some time to investigate on the weekend

**Comment by JanGorman** [comment]
I've done some investigation but no solution yet. But I'm on it

**Comment by Alexookah** [comment]
@JanGorman  anything new?

**Comment by JanGorman** [comment]
My investigation at the time yielded that while I can reproduce the problem, no good indication as to how it can be fixed in the current setup and then I got distracted 😢 Help welcome

**Comment by Alexookah** [comment]
Ok sure, could you tell us your investigation results? 
some details of where the problem is so that me and other people may take a look

**Comment by JanGorman** [comment]
Thanks!

Good thing I kept some notes, let's see if I can make sense of them… I launched a sample app and then entered the view debugger, what I noticed:
- UICollectionView bounds have a negative origin
- when you start dragging the image and release it, the imageView jumps to the correct center
- after it's correctly centered, the image frame is slightly smaller and at origin .zero
- the imageView is embedded in a UIScrollView and there's a discrepancy in frame sizes

I did a bunch of things like modifying the values through the debug console but that had no effect.

It's not a lot to go on and I'm still unsure if it's the right area to focus on but the sizes/origins at least _seem_ a good place to start

**Comment by Alexookah** [comment]
https://github.com/JanGorman/Agrume/blob/master/Agrume/AgrumeCell.swift#L217
`return UIEdgeInsets(top: verticalDiff, left: horizontalDiff / 2, bottom: verticalDiff, right: horizontalDiff / 2)
`
I changed to / 2 and i tried to open an image is landscape.

![landscape photo](https://user-images.githubusercontent.com/9624843/69544013-84295100-0f97-11ea-8163-fc14ff3ff883.png)

it seems that it initialized correct but after dragging it goes to wrong place

then i tried to open a portait photo in lanscape and it initialzed wrong

![portait photo](https://user-images.githubusercontent.com/9624843/69544078-a7540080-0f97-11ea-9f8f-86db35d821fe.png)

maybe the insets are conficliting something?

**Comment by JanGorman** [comment]
good point… I only remembered later that I also tweaked some values when testing and came to something similar to what you found. Worth digging further

**Comment by Alexookah** [comment]
@JanGorman Finally found the issue. 
I want to make another PL with my resolution but it seems i have already one ongoing.
Can you take a look https://github.com/JanGorman/Agrume/pull/133

**Comment by Alexookah** [comment]
i did another PL
@JanGorman 
FINALLY found the issue. Eventually after debuging frame's and bounds. 
It got me thinking about 
"UICollectionView bounds have a negative origin".

it such a simple fix check it out:
https://github.com/JanGorman/Agrume/pull/134

**Comment by Alexookah** [comment]
closing this issue since this fix has been merged in master
