### ISSUE TITLE
Close button with drag feature

### ISSUE THREAD

**Issue by Alexookah** [JanGorman/Agrume#97]
i used the close button and i saw that the drag feature is disabled.
there should be an option to show closebutton with drag feature.

**Comment by JanGorman** [comment]
Would you like the full drag feature or just e.g. a pull down or up (as that's a quite common pattern)?

**Comment by hemangshah** [comment]
I was about to open same issue. Currently, we can use either of them:

`Agrume.init(image: image, background: .blurred(.dark), dismissal: .withButton(button))`

**or** 

`Agrume.init(image: image, background: .blurred(.dark), dismissal: .withPhysics)`

**Is there any way we can setup both together?**

**Why both**? Some users don't know how to close it so for them a **X** button is require for others with physics.

**Comment by hemangshah** [comment]
Thanks @JanGorman 🎉

**Comment by hemangshah** [comment]
Agrume.init(image: image, background: .blurred(.dark), dismissal: .withPhysicsAndButton(button)).show(from: self)
